#define STRINGIFY_HELPER(x) #x
#define STRINGIFY(x) STRINGIFY_HELPER(x)

#define RDK_HALIF_DEVICE_SETTINGS_VERSION_STR  \
    STRINGIFY(RDK_HALIF_DEVICE_SETTINGS_VERSION_MAJOR) "." \
    STRINGIFY(RDK_HALIF_DEVICE_SETTINGS_VERSION_MINOR) "." \
    STRINGIFY(RDK_HALIF_DEVICE_SETTINGS_VERSION_BUILD) "." \
    STRINGIFY(RDK_HALIF_DEVICE_SETTINGS_VERSION_ENGINEERING)


#define RDK_HALIF_DEVICE_SETTINGS_VERSION  \
        ((RDK_HALIF_DEVICE_SETTINGS_VERSION_MAJOR << 24) | \
         (RDK_HALIF_DEVICE_SETTINGS_VERSION_MINOR << 16) | \
         (RDK_HALIF_DEVICE_SETTINGS_VERSION_BUILD << 8)  | \
         (RDK_HALIF_DEVICE_SETTINGS_VERSION_ENGINEERING))
