pcm.hdmi_sink {
    type plug
    slave {
        pcm "iec958:CARD=vc4hdmi0,DEV=0"
        format S16_LE
        rate 48000
        channels 2
    }
}

pcm.hdmi_softvol {
    type softvol
    slave.pcm "hdmi_sink"
    control {
        name "SoftMaster"
        card 0
    }
    min_dB -51.0
    max_dB 0.0
    resolution 256
}

pcm.!default {
    type plug
    slave.pcm "hdmi_softvol"
}

ctl.!default {
    type hw
    card 0
}
